name: yippy_lingo_demo
description: Demo for YippyLingo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_lints: ^2.0.0

  # architecture
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # dependency injection
  get_it: ^7.6.0

  # functional programming, used for Either type

  # logger:
  logger: ^1.3.0

  # equatable:
  equatable: ^2.0.5
  http: ^0.13.6
  mocktail: ^0.3.0
  infinite_carousel: ^1.0.3
  page_view_dot_indicator: ^2.1.0
  go_router: ^9.0.0
  golden_toolkit: ^0.15.0
  alchemist: ^0.6.1
  mocktail_image_network: ^0.3.1
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

